server:
  port: 8006
spring:
  application:
    name: attention_8006
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://39.98.240.68:3306/apollo?userUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 123

eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://39.98.240.68:8000/eureka/

mybatis:
  type-aliases-package: com.bittereggs.attention_8006.entity
  mapper-locations: classpath:mybatis/*.xml