server:
  port: 8004
spring:
  application:
    name: fillinformation_8004
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/apollo?userUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 123456
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200
eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://localhost:8000/eureka/

mybatis:
  type-aliases-package: com.alpha.fillinformation_8004.entity
  mapper-locations: classpath:mybatis.mapper/*.xml
